import { course_images } from './images';

const courses = [
  {
    id: 'xMHCZl',
    category: 'python',
    image: course_images.python_5,
    course_name: 'Learn Python: The Complete Python Programming Course',
    description:
      'Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!',
    rating_count: 3059,
    rating_star: 4.4,
    students: 18430,
    creator: 'Avinash Jain, The Codex',
    updated_date: '9/2015',
    lang: 'english',
    actual_price: 84.99,
    discounted_price: 9.99,
    what_you_will_learn: [
      'Create their own Python Programs',
      'Become an experienced Python Programmer',
      'Parse the Web and Create their own Games',
    ],
    content: [
      'Up and Running With Python',
      'The Basics(Data Types)',
      'Conditions and Loops',
      'Functions!',
      'Classes! (Object Oriented Programming)',
      'File Input/Output',
      'Using Python Modules',
    ],
  },
  {
    id: 'dtfo9e',
    category: 'python',
    image: course_images.python_4,
    course_name: 'Learning Python for Data Analysis and Visualization',
    description:
      'Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!',
    rating_count: 3059,
    rating_star: 4.3,
    students: 184053,
    creator: 'Jose Portilla',
    updated_date: '9/2019',
    lang: 'english',
    actual_price: 84.99,
    discounted_price: 9.99,
    what_you_will_learn: [
      'Have an intermediate skill level of Python programming.',
      'Use the numpy library to create and manipulate arrays.',
      'Learn how to work with various data formats within python, including: JSON,HTML, and MS Excel Worksheets.',
      'Have a portfolio of various data analysis projects.',
    ],
    content: [
      'Intro to Course and Python',
      'Learning Numpy',
      'Data Visualization',
      'Example Projects',
      'Machine Learning',
      'SQL and Python',
      'Web Scraping with Python',
    ],
  },
  {
    id: 'fLroW6',
    category: 'python',
    image: course_images.python_3,
    course_name: 'Python for Beginners - Learn Programming from scratch',
    description:
      'Python For Beginners : This course is meant for absolute beginners in programming or in python!',
    rating_count: 1844,
    rating_star: 4.3,
    students: 7330,
    creator: 'Edwin Diaz, Coding Faculty Solutionss',
    updated_date: '5/2022',
    lang: 'english',
    actual_price: 84.99,
    discounted_price: 9.99,
    what_you_will_learn: [
      'To learn the python language',
      'To learn the CORE skills to understand any programming language',
    ],
    content: [
      'Programming fundamentals',
      'Getting Started with Python',
      'Python Basics',
      'Conditional structures',
      'Functions',
      'Working with files',
    ],
  },
  {
    id: 'VwkN_o',
    category: 'python',
    image: course_images.python_2,
    course_name:
      'Python For Beginners : This course is meant for absolute beginners in programming or in python.',
    description:
      'Python introduction for beginners. Learn complete Python from scratch!',
    rating_count: 2780,
    rating_star: 4.3,
    students: 29082,
    creator: 'Abrar Hussain',
    updated_date: '9/2019',
    lang: 'english',
    actual_price: 29.99,
    discounted_price: 9.99,
    what_you_will_learn: [
      'Create fully functional Python programs',
      'Learn about loop structures and conditionals',
      'Work with Python file handling',
      'Manipulate strings and data',
    ],
    content: [
      'Getting Started',
      'The Basics',
      'User Input',
      'Functions and Files',
      'Classes and Objects',
      'Graphics and Animations',
    ],
  },
  {
    id: 'xJB-WU',
    category: 'python',
    image: course_images.python_1,
    course_name: 'Python Beyond the Basics - Object-Oriented Programming',
    description:
      'From Classes To Inheritance - OOP In-Depth For Python Programmers',
    rating_count: 2941,
    rating_star: 4.2,
    students: 10450,
    creator: 'Infinite Skills',
    updated_date: '9/2019',
    lang: 'english',
    actual_price: 49.99,
    discounted_price: 10.99,
    what_you_will_learn: [
      'Design Reusable Object-Oriented Python Classes',
      'How to handle Errors',
      'Work with Python file handling',
      'Apply OOP Concepts to handle complexity',
    ],
    content: [
      'Introduction to Object Oriented Python',
      'Classes',
      'Inhertiance and Polymorphism',
      'Advanced Features',
      'Object Serialization',
      'Efficiency and testing',
      'Conclusion',
    ],
  },
];

export default courses;
